"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.exposeAll = exports.exposeIt = exports.expose = exports.inspectIt = exports.inspect = exports.checkIt = exports.check = exports.acceptIt = exports.accept = exports.captureAll = exports.captureIt = exports.capture = void 0;
var capture_1 = require("./functions/capture");
Object.defineProperty(exports, "capture", { enumerable: true, get: function () { return capture_1.capture; } });
Object.defineProperty(exports, "captureIt", { enumerable: true, get: function () { return capture_1.captureIt; } });
Object.defineProperty(exports, "captureAll", { enumerable: true, get: function () { return capture_1.captureAll; } });
var accept_1 = require("./functions/accept");
Object.defineProperty(exports, "accept", { enumerable: true, get: function () { return accept_1.accept; } });
Object.defineProperty(exports, "acceptIt", { enumerable: true, get: function () { return accept_1.acceptIt; } });
var check_1 = require("./functions/check");
Object.defineProperty(exports, "check", { enumerable: true, get: function () { return check_1.check; } });
Object.defineProperty(exports, "checkIt", { enumerable: true, get: function () { return check_1.checkIt; } });
var inspect_1 = require("./functions/inspect");
Object.defineProperty(exports, "inspect", { enumerable: true, get: function () { return inspect_1.inspect; } });
Object.defineProperty(exports, "inspectIt", { enumerable: true, get: function () { return inspect_1.inspectIt; } });
var expose_1 = require("./functions/expose");
Object.defineProperty(exports, "expose", { enumerable: true, get: function () { return expose_1.expose; } });
Object.defineProperty(exports, "exposeIt", { enumerable: true, get: function () { return expose_1.exposeIt; } });
Object.defineProperty(exports, "exposeAll", { enumerable: true, get: function () { return expose_1.exposeAll; } });
//# sourceMappingURL=index.js.map