export { capture, captureIt, captureAll } from './functions/capture'
export { accept, acceptIt } from './functions/accept'
export { check, checkIt } from './functions/check'
export { inspect, inspectIt } from './functions/inspect'
export { expose, exposeIt, exposeAll } from './functions/expose'
