import './Code/Assertion.ts'
import './Code/Combinatorics.ts'
import './Code/Flow.ts'
import './Code/Fraction.ts'
import './Code/Function.ts'
import './Code/Geometry.ts'
import './Code/LinearProgram.ts'
import './Code/Numeracy.ts'
import './Code/PhyConst.ts'
import './Code/Random.ts'
import './Code/RandomShake.ts'
import './Code/RandomUtil.ts'
import './Code/Relation.ts'
import './Code/Sequence.ts'
import './Code/Stat.ts'
import './Code/Text.ts'
import './Code/Triangle.ts'
import './Code/Trigonometry.ts'
import './Code/Utility.ts'
import './Code/Vector.ts'

import './Algebra/Algebra.ts'
import './Algebra/Circle.ts'
import './Algebra/Quadratic.ts'
import './Algebra/Linear.ts'


import './should.ts'
import './chance.ts'