// This file is auto-generated by expose.ts

import * as bundle from './bundle.js'

declare global {
    var ASTC: typeof bundle.ASTC
    var ASequence: typeof bundle.ASequence
    var ASsum: typeof bundle.ASsum
    var ASterm: typeof bundle.ASterm
    var Abs: typeof bundle.Abs
    var Angle: typeof bundle.Angle
    var AnglePolar: typeof bundle.AnglePolar
    var ArcLength: typeof bundle.ArcLength
    var AreAbsDistinct: typeof bundle.AreAbsDistinct
    var AreCoprime: typeof bundle.AreCoprime
    var AreDifferent: typeof bundle.AreDifferent
    var AreDistantPoint: typeof bundle.AreDistantPoint
    var AreDistinct: typeof bundle.AreDistinct
    var AreOblique: typeof bundle.AreOblique
    var AreSameSign: typeof bundle.AreSameSign
    var ArrangePoints: typeof bundle.ArrangePoints
    var At: typeof bundle.At
    var Bin: typeof bundle.Bin
    var Binomial: typeof bundle.Binomial
    var BuildAngle: typeof bundle.BuildAngle
    var BuildRatio: typeof bundle.BuildRatio
    var BuildSolve: typeof bundle.BuildSolve
    var BuildTrend: typeof bundle.BuildTrend
    var Ceil: typeof bundle.Ceil
    var Centroid: typeof bundle.Centroid
    var CheckVertices: typeof bundle.CheckVertices
    var ChessboardDistance: typeof bundle.ChessboardDistance
    var CircleFromGeneral: typeof bundle.CircleFromGeneral
    var CircleGeneral: typeof bundle.CircleGeneral
    var CircleLineIntersect: typeof bundle.CircleLineIntersect
    var CircleLinearIntersect: typeof bundle.CircleLinearIntersect
    var Circumcentre: typeof bundle.Circumcentre
    var ComboDisplay: typeof bundle.ComboDisplay
    var CompassBearing: typeof bundle.CompassBearing
    var ConstraintText: typeof bundle.ConstraintText
    var ConstraintsFromPoints: typeof bundle.ConstraintsFromPoints
    var Coord: typeof bundle.Coord
    var CosineLawAngle: typeof bundle.CosineLawAngle
    var CosineLawLength: typeof bundle.CosineLawLength
    var Crammer: typeof bundle.Crammer
    var Degree: typeof bundle.Degree
    var Dfrac: typeof bundle.Dfrac
    var Dir: typeof bundle.Dir
    var Discriminant: typeof bundle.Discriminant
    var Distance: typeof bundle.Distance
    var Divide: typeof bundle.Divide
    var Embed: typeof bundle.Embed
    var EmbedX: typeof bundle.EmbedX
    var EmbedY: typeof bundle.EmbedY
    var EmbedZ: typeof bundle.EmbedZ
    var ExplainTransforms: typeof bundle.ExplainTransforms
    var Extrude: typeof bundle.Extrude
    var Factorial: typeof bundle.Factorial
    var FeasibleIntegral: typeof bundle.FeasibleIntegral
    var FeasibleIsBounded: typeof bundle.FeasibleIsBounded
    var FeasiblePolygon: typeof bundle.FeasiblePolygon
    var FeasibleVertices: typeof bundle.FeasibleVertices
    var FieldAt: typeof bundle.FieldAt
    var Fix: typeof bundle.Fix
    var FixDown: typeof bundle.FixDown
    var FixUp: typeof bundle.FixUp
    var FlatZ: typeof bundle.FlatZ
    var Floor: typeof bundle.Floor
    var Flop: typeof bundle.Flop
    var Freq: typeof bundle.Freq
    var FreqTable: typeof bundle.FreqTable
    var Freqs: typeof bundle.Freqs
    var GSequence: typeof bundle.GSequence
    var GSsum: typeof bundle.GSsum
    var GSterm: typeof bundle.GSterm
    var GrammarJoin: typeof bundle.GrammarJoin
    var GroupCumFreqTable: typeof bundle.GroupCumFreqTable
    var GroupFreqTable: typeof bundle.GroupFreqTable
    var HCF: typeof bundle.HCF
    var HeightBySAS: typeof bundle.HeightBySAS
    var HeightBySSS: typeof bundle.HeightBySSS
    var HeightsBySAS: typeof bundle.HeightsBySAS
    var HeightsBySSS: typeof bundle.HeightsBySSS
    var Heron: typeof bundle.Heron
    var IQR: typeof bundle.IQR
    var Incentre: typeof bundle.Incentre
    var IndexToSurd: typeof bundle.IndexToSurd
    var IneqSign: typeof bundle.IneqSign
    var IntersectAngle: typeof bundle.IntersectAngle
    var Intersection: typeof bundle.Intersection
    var IsAbsBetween: typeof bundle.IsAbsBetween
    var IsAroundPoint: typeof bundle.IsAroundPoint
    var IsBetween: typeof bundle.IsBetween
    var IsConvexPolygon: typeof bundle.IsConvexPolygon
    var IsDecimal: typeof bundle.IsDecimal
    var IsEven: typeof bundle.IsEven
    var IsInteger: typeof bundle.IsInteger
    var IsNegative: typeof bundle.IsNegative
    var IsNonNegative: typeof bundle.IsNonNegative
    var IsNonNegativeInteger: typeof bundle.IsNonNegativeInteger
    var IsNonZero: typeof bundle.IsNonZero
    var IsNum: typeof bundle.IsNum
    var IsOdd: typeof bundle.IsOdd
    var IsPositive: typeof bundle.IsPositive
    var IsPositiveInteger: typeof bundle.IsPositiveInteger
    var IsProbability: typeof bundle.IsProbability
    var IsRational: typeof bundle.IsRational
    var IsReflex: typeof bundle.IsReflex
    var IsSquareNum: typeof bundle.IsSquareNum
    var IsTerminating: typeof bundle.IsTerminating
    var IsTriangle: typeof bundle.IsTriangle
    var LCM: typeof bundle.LCM
    var Lace: typeof bundle.Lace
    var LineFeat: typeof bundle.LineFeat
    var LineFromBisector: typeof bundle.LineFromBisector
    var LineFromIntercepts: typeof bundle.LineFromIntercepts
    var LineFromPointSlope: typeof bundle.LineFromPointSlope
    var LineFromTwoPoints: typeof bundle.LineFromTwoPoints
    var LinearFromBisector: typeof bundle.LinearFromBisector
    var LinearFromIntercepts: typeof bundle.LinearFromIntercepts
    var LinearFromPointSlope: typeof bundle.LinearFromPointSlope
    var LinearFromTwoPoints: typeof bundle.LinearFromTwoPoints
    var LongDivision: typeof bundle.LongDivision
    var LowerQ: typeof bundle.LowerQ
    var LowerQAt: typeof bundle.LowerQAt
    var LucasSequence: typeof bundle.LucasSequence
    var Max: typeof bundle.Max
    var MaximizeField: typeof bundle.MaximizeField
    var MaximizePoint: typeof bundle.MaximizePoint
    var Mean: typeof bundle.Mean
    var Median: typeof bundle.Median
    var MedianAt: typeof bundle.MedianAt
    var Mid: typeof bundle.Mid
    var Mid3D: typeof bundle.Mid3D
    var Min: typeof bundle.Min
    var MinimizeField: typeof bundle.MinimizeField
    var MinimizePoint: typeof bundle.MinimizePoint
    var Mode: typeof bundle.Mode
    var Move: typeof bundle.Move
    var MoveX: typeof bundle.MoveX
    var MoveY: typeof bundle.MoveY
    var OnCircle: typeof bundle.OnCircle
    var OptimizeField: typeof bundle.OptimizeField
    var OptimizePoint: typeof bundle.OptimizePoint
    var Orthocentre: typeof bundle.Orthocentre
    var PairTable: typeof bundle.PairTable
    var Partition: typeof bundle.Partition
    var PdFoot: typeof bundle.PdFoot
    var PdFoot3D: typeof bundle.PdFoot3D
    var PhyConst: typeof bundle.PhyConst
    var PhyEq: typeof bundle.PhyEq
    var PolToRect: typeof bundle.PolToRect
    var PolarDiff: typeof bundle.PolarDiff
    var PolarReduce: typeof bundle.PolarReduce
    var PolyFunction: typeof bundle.PolyFunction
    var PolyPrint: typeof bundle.PolyPrint
    var PolySimplify: typeof bundle.PolySimplify
    var PolySort: typeof bundle.PolySort
    var PrimeFactorize: typeof bundle.PrimeFactorize
    var PrimeFactors: typeof bundle.PrimeFactors
    var Product: typeof bundle.Product
    var Pyth: typeof bundle.Pyth
    var PythLeg: typeof bundle.PythLeg
    var Quadrant: typeof bundle.Quadrant
    var QuadraticFromRoot: typeof bundle.QuadraticFromRoot
    var QuadraticFromVertex: typeof bundle.QuadraticFromVertex
    var QuadraticRoot: typeof bundle.QuadraticRoot
    var QuadraticSequence: typeof bundle.QuadraticSequence
    var QuadraticVertex: typeof bundle.QuadraticVertex
    var Radian: typeof bundle.Radian
    var Ratio: typeof bundle.Ratio
    var RectToPol: typeof bundle.RectToPol
    var ReflectX: typeof bundle.ReflectX
    var ReflectY: typeof bundle.ReflectY
    var RegularPolygon: typeof bundle.RegularPolygon
    var RndAngles: typeof bundle.RndAngles
    var RndCapitals: typeof bundle.RndCapitals
    var RndComposite: typeof bundle.RndComposite
    var RndConvexPolygon: typeof bundle.RndConvexPolygon
    var RndData: typeof bundle.RndData
    var RndEven: typeof bundle.RndEven
    var RndHe: typeof bundle.RndHe
    var RndLetters: typeof bundle.RndLetters
    var RndN: typeof bundle.RndN
    var RndNs: typeof bundle.RndNs
    var RndOdd: typeof bundle.RndOdd
    var RndOnCircle: typeof bundle.RndOnCircle
    var RndP: typeof bundle.RndP
    var RndPartition: typeof bundle.RndPartition
    var RndPick: typeof bundle.RndPick
    var RndPickN: typeof bundle.RndPickN
    var RndPickUnique: typeof bundle.RndPickUnique
    var RndPoint: typeof bundle.RndPoint
    var RndPointPolar: typeof bundle.RndPointPolar
    var RndPoints: typeof bundle.RndPoints
    var RndPoly: typeof bundle.RndPoly
    var RndPolynomial: typeof bundle.RndPolynomial
    var RndPyth: typeof bundle.RndPyth
    var RndQ: typeof bundle.RndQ
    var RndQs: typeof bundle.RndQs
    var RndR: typeof bundle.RndR
    var RndRatio: typeof bundle.RndRatio
    var RndRs: typeof bundle.RndRs
    var RndShake: typeof bundle.RndShake
    var RndShakeBase: typeof bundle.RndShakeBase
    var RndShakeCombo: typeof bundle.RndShakeCombo
    var RndShakeCompoundInequality: typeof bundle.RndShakeCompoundInequality
    var RndShakeConstraint: typeof bundle.RndShakeConstraint
    var RndShakeConstraints: typeof bundle.RndShakeConstraints
    var RndShakeG: typeof bundle.RndShakeG
    var RndShakeIneq: typeof bundle.RndShakeIneq
    var RndShakeN: typeof bundle.RndShakeN
    var RndShakePoint: typeof bundle.RndShakePoint
    var RndShakePointPolar: typeof bundle.RndShakePointPolar
    var RndShakeQ: typeof bundle.RndShakeQ
    var RndShakeQuantity: typeof bundle.RndShakeQuantity
    var RndShakeR: typeof bundle.RndShakeR
    var RndShakeRatio: typeof bundle.RndShakeRatio
    var RndShakeTrig: typeof bundle.RndShakeTrig
    var RndShakeTrigValue: typeof bundle.RndShakeTrigValue
    var RndShe: typeof bundle.RndShe
    var RndShuffle: typeof bundle.RndShuffle
    var RndT: typeof bundle.RndT
    var RndTriangle: typeof bundle.RndTriangle
    var RndTrigEqv: typeof bundle.RndTrigEqv
    var RndTrigValue: typeof bundle.RndTrigValue
    var RndU: typeof bundle.RndU
    var RndZ: typeof bundle.RndZ
    var RndZs: typeof bundle.RndZs
    var Rng: typeof bundle.Rng
    var Rotate: typeof bundle.Rotate
    var Round: typeof bundle.Round
    var RoundDown: typeof bundle.RoundDown
    var RoundUp: typeof bundle.RoundUp
    var ScaleCentroidToInt: typeof bundle.ScaleCentroidToInt
    var ScaleCircumcentreToInt: typeof bundle.ScaleCircumcentreToInt
    var ScaleIncentreToInt: typeof bundle.ScaleIncentreToInt
    var ScaleOrthocentreToInt: typeof bundle.ScaleOrthocentreToInt
    var ScaleTo: typeof bundle.ScaleTo
    var Sci: typeof bundle.Sci
    var SectorArea: typeof bundle.SectorArea
    var ShakeBase: typeof bundle.ShakeBase
    var ShakeCompoundInequality: typeof bundle.ShakeCompoundInequality
    var ShakeConstraint: typeof bundle.ShakeConstraint
    var ShakeConstraints: typeof bundle.ShakeConstraints
    var ShakeG: typeof bundle.ShakeG
    var ShakeIneq: typeof bundle.ShakeIneq
    var ShakeN: typeof bundle.ShakeN
    var ShakePoint: typeof bundle.ShakePoint
    var ShakePointPolar: typeof bundle.ShakePointPolar
    var ShakeQ: typeof bundle.ShakeQ
    var ShakeQuantity: typeof bundle.ShakeQuantity
    var ShakeR: typeof bundle.ShakeR
    var ShakeRatio: typeof bundle.ShakeRatio
    var ShakeTrigValue: typeof bundle.ShakeTrigValue
    var ShortDivision: typeof bundle.ShortDivision
    var ShortDivisionBy2: typeof bundle.ShortDivisionBy2
    var SigFig: typeof bundle.SigFig
    var Sign: typeof bundle.Sign
    var SineLawAngle: typeof bundle.SineLawAngle
    var SineLawLength: typeof bundle.SineLawLength
    var Slide: typeof bundle.Slide
    var Slide3D: typeof bundle.Slide3D
    var Slope: typeof bundle.Slope
    var SlopePd: typeof bundle.SlopePd
    var SolveAAS: typeof bundle.SolveAAS
    var SolveASA: typeof bundle.SolveASA
    var SolveSAS: typeof bundle.SolveSAS
    var SolveSSA: typeof bundle.SolveSSA
    var SolveSSS: typeof bundle.SolveSSS
    var SolveTriangle: typeof bundle.SolveTriangle
    var Sort: typeof bundle.Sort
    var SortBy: typeof bundle.SortBy
    var Sqrt: typeof bundle.Sqrt
    var StatRange: typeof bundle.StatRange
    var StdDev: typeof bundle.StdDev
    var StemAndLeaf: typeof bundle.StemAndLeaf
    var Sum: typeof bundle.Sum
    var Summary: typeof bundle.Summary
    var Table: typeof bundle.Table
    var ToBase: typeof bundle.ToBase
    var ToFrac: typeof bundle.ToFrac
    var TransformFunc: typeof bundle.TransformFunc
    var TriangleFromPoint: typeof bundle.TriangleFromPoint
    var TriangleFromVertex: typeof bundle.TriangleFromVertex
    var TrigSolve: typeof bundle.TrigSolve
    var UniMode: typeof bundle.UniMode
    var UpperQ: typeof bundle.UpperQ
    var UpperQAt: typeof bundle.UpperQAt
    var VecAdd: typeof bundle.VecAdd
    var VecAdd3D: typeof bundle.VecAdd3D
    var WholeBearing: typeof bundle.WholeBearing
    var ZScore: typeof bundle.ZScore
    var arccos: typeof bundle.arccos
    var arcsin: typeof bundle.arcsin
    var arctan: typeof bundle.arctan
    var cos: typeof bundle.cos
    var deepBlurize: typeof bundle.deepBlurize
    var differentiate: typeof bundle.differentiate
    var functionize: typeof bundle.functionize
    var getMaxDeg: typeof bundle.getMaxDeg
    var integrate: typeof bundle.integrate
    var isConstrained: typeof bundle.isConstrained
    var isLooseConstrained: typeof bundle.isLooseConstrained
    var log: typeof bundle.log
    var nCr: typeof bundle.nCr
    var nPr: typeof bundle.nPr
    var sin: typeof bundle.sin
    var tan: typeof bundle.tan
    var xPolynomial: typeof bundle.xPolynomial
}

globalThis.ASTC = bundle.deepBlurize(bundle.ASTC)
globalThis.ASequence = bundle.deepBlurize(bundle.ASequence)
globalThis.ASsum = bundle.deepBlurize(bundle.ASsum)
globalThis.ASterm = bundle.deepBlurize(bundle.ASterm)
globalThis.Abs = bundle.deepBlurize(bundle.Abs)
globalThis.Angle = bundle.deepBlurize(bundle.Angle)
globalThis.AnglePolar = bundle.deepBlurize(bundle.AnglePolar)
globalThis.ArcLength = bundle.deepBlurize(bundle.ArcLength)
globalThis.AreAbsDistinct = bundle.deepBlurize(bundle.AreAbsDistinct)
globalThis.AreCoprime = bundle.deepBlurize(bundle.AreCoprime)
globalThis.AreDifferent = bundle.deepBlurize(bundle.AreDifferent)
globalThis.AreDistantPoint = bundle.deepBlurize(bundle.AreDistantPoint)
globalThis.AreDistinct = bundle.deepBlurize(bundle.AreDistinct)
globalThis.AreOblique = bundle.deepBlurize(bundle.AreOblique)
globalThis.AreSameSign = bundle.deepBlurize(bundle.AreSameSign)
globalThis.ArrangePoints = bundle.deepBlurize(bundle.ArrangePoints)
globalThis.At = bundle.deepBlurize(bundle.At)
globalThis.Bin = bundle.deepBlurize(bundle.Bin)
globalThis.Binomial = bundle.deepBlurize(bundle.Binomial)
globalThis.BuildAngle = bundle.deepBlurize(bundle.BuildAngle)
globalThis.BuildRatio = bundle.deepBlurize(bundle.BuildRatio)
globalThis.BuildSolve = bundle.deepBlurize(bundle.BuildSolve)
globalThis.BuildTrend = bundle.deepBlurize(bundle.BuildTrend)
globalThis.Ceil = bundle.deepBlurize(bundle.Ceil)
globalThis.Centroid = bundle.deepBlurize(bundle.Centroid)
globalThis.CheckVertices = bundle.deepBlurize(bundle.CheckVertices)
globalThis.ChessboardDistance = bundle.deepBlurize(bundle.ChessboardDistance)
globalThis.CircleFromGeneral = bundle.deepBlurize(bundle.CircleFromGeneral)
globalThis.CircleGeneral = bundle.deepBlurize(bundle.CircleGeneral)
globalThis.CircleLineIntersect = bundle.deepBlurize(bundle.CircleLineIntersect)
globalThis.CircleLinearIntersect = bundle.deepBlurize(bundle.CircleLinearIntersect)
globalThis.Circumcentre = bundle.deepBlurize(bundle.Circumcentre)
globalThis.ComboDisplay = bundle.deepBlurize(bundle.ComboDisplay)
globalThis.CompassBearing = bundle.deepBlurize(bundle.CompassBearing)
globalThis.ConstraintText = bundle.deepBlurize(bundle.ConstraintText)
globalThis.ConstraintsFromPoints = bundle.deepBlurize(bundle.ConstraintsFromPoints)
globalThis.Coord = bundle.deepBlurize(bundle.Coord)
globalThis.CosineLawAngle = bundle.deepBlurize(bundle.CosineLawAngle)
globalThis.CosineLawLength = bundle.deepBlurize(bundle.CosineLawLength)
globalThis.Crammer = bundle.deepBlurize(bundle.Crammer)
globalThis.Degree = bundle.deepBlurize(bundle.Degree)
globalThis.Dfrac = bundle.deepBlurize(bundle.Dfrac)
globalThis.Dir = bundle.deepBlurize(bundle.Dir)
globalThis.Discriminant = bundle.deepBlurize(bundle.Discriminant)
globalThis.Distance = bundle.deepBlurize(bundle.Distance)
globalThis.Divide = bundle.deepBlurize(bundle.Divide)
globalThis.Embed = bundle.deepBlurize(bundle.Embed)
globalThis.EmbedX = bundle.deepBlurize(bundle.EmbedX)
globalThis.EmbedY = bundle.deepBlurize(bundle.EmbedY)
globalThis.EmbedZ = bundle.deepBlurize(bundle.EmbedZ)
globalThis.ExplainTransforms = bundle.deepBlurize(bundle.ExplainTransforms)
globalThis.Extrude = bundle.deepBlurize(bundle.Extrude)
globalThis.Factorial = bundle.deepBlurize(bundle.Factorial)
globalThis.FeasibleIntegral = bundle.deepBlurize(bundle.FeasibleIntegral)
globalThis.FeasibleIsBounded = bundle.deepBlurize(bundle.FeasibleIsBounded)
globalThis.FeasiblePolygon = bundle.deepBlurize(bundle.FeasiblePolygon)
globalThis.FeasibleVertices = bundle.deepBlurize(bundle.FeasibleVertices)
globalThis.FieldAt = bundle.deepBlurize(bundle.FieldAt)
globalThis.Fix = bundle.deepBlurize(bundle.Fix)
globalThis.FixDown = bundle.deepBlurize(bundle.FixDown)
globalThis.FixUp = bundle.deepBlurize(bundle.FixUp)
globalThis.FlatZ = bundle.deepBlurize(bundle.FlatZ)
globalThis.Floor = bundle.deepBlurize(bundle.Floor)
globalThis.Flop = bundle.deepBlurize(bundle.Flop)
globalThis.Freq = bundle.deepBlurize(bundle.Freq)
globalThis.FreqTable = bundle.deepBlurize(bundle.FreqTable)
globalThis.Freqs = bundle.deepBlurize(bundle.Freqs)
globalThis.GSequence = bundle.deepBlurize(bundle.GSequence)
globalThis.GSsum = bundle.deepBlurize(bundle.GSsum)
globalThis.GSterm = bundle.deepBlurize(bundle.GSterm)
globalThis.GrammarJoin = bundle.deepBlurize(bundle.GrammarJoin)
globalThis.GroupCumFreqTable = bundle.deepBlurize(bundle.GroupCumFreqTable)
globalThis.GroupFreqTable = bundle.deepBlurize(bundle.GroupFreqTable)
globalThis.HCF = bundle.deepBlurize(bundle.HCF)
globalThis.HeightBySAS = bundle.deepBlurize(bundle.HeightBySAS)
globalThis.HeightBySSS = bundle.deepBlurize(bundle.HeightBySSS)
globalThis.HeightsBySAS = bundle.deepBlurize(bundle.HeightsBySAS)
globalThis.HeightsBySSS = bundle.deepBlurize(bundle.HeightsBySSS)
globalThis.Heron = bundle.deepBlurize(bundle.Heron)
globalThis.IQR = bundle.deepBlurize(bundle.IQR)
globalThis.Incentre = bundle.deepBlurize(bundle.Incentre)
globalThis.IndexToSurd = bundle.deepBlurize(bundle.IndexToSurd)
globalThis.IneqSign = bundle.deepBlurize(bundle.IneqSign)
globalThis.IntersectAngle = bundle.deepBlurize(bundle.IntersectAngle)
globalThis.Intersection = bundle.deepBlurize(bundle.Intersection)
globalThis.IsAbsBetween = bundle.deepBlurize(bundle.IsAbsBetween)
globalThis.IsAroundPoint = bundle.deepBlurize(bundle.IsAroundPoint)
globalThis.IsBetween = bundle.deepBlurize(bundle.IsBetween)
globalThis.IsConvexPolygon = bundle.deepBlurize(bundle.IsConvexPolygon)
globalThis.IsDecimal = bundle.deepBlurize(bundle.IsDecimal)
globalThis.IsEven = bundle.deepBlurize(bundle.IsEven)
globalThis.IsInteger = bundle.deepBlurize(bundle.IsInteger)
globalThis.IsNegative = bundle.deepBlurize(bundle.IsNegative)
globalThis.IsNonNegative = bundle.deepBlurize(bundle.IsNonNegative)
globalThis.IsNonNegativeInteger = bundle.deepBlurize(bundle.IsNonNegativeInteger)
globalThis.IsNonZero = bundle.deepBlurize(bundle.IsNonZero)
globalThis.IsNum = bundle.deepBlurize(bundle.IsNum)
globalThis.IsOdd = bundle.deepBlurize(bundle.IsOdd)
globalThis.IsPositive = bundle.deepBlurize(bundle.IsPositive)
globalThis.IsPositiveInteger = bundle.deepBlurize(bundle.IsPositiveInteger)
globalThis.IsProbability = bundle.deepBlurize(bundle.IsProbability)
globalThis.IsRational = bundle.deepBlurize(bundle.IsRational)
globalThis.IsReflex = bundle.deepBlurize(bundle.IsReflex)
globalThis.IsSquareNum = bundle.deepBlurize(bundle.IsSquareNum)
globalThis.IsTerminating = bundle.deepBlurize(bundle.IsTerminating)
globalThis.IsTriangle = bundle.deepBlurize(bundle.IsTriangle)
globalThis.LCM = bundle.deepBlurize(bundle.LCM)
globalThis.Lace = bundle.deepBlurize(bundle.Lace)
globalThis.LineFeat = bundle.deepBlurize(bundle.LineFeat)
globalThis.LineFromBisector = bundle.deepBlurize(bundle.LineFromBisector)
globalThis.LineFromIntercepts = bundle.deepBlurize(bundle.LineFromIntercepts)
globalThis.LineFromPointSlope = bundle.deepBlurize(bundle.LineFromPointSlope)
globalThis.LineFromTwoPoints = bundle.deepBlurize(bundle.LineFromTwoPoints)
globalThis.LinearFromBisector = bundle.deepBlurize(bundle.LinearFromBisector)
globalThis.LinearFromIntercepts = bundle.deepBlurize(bundle.LinearFromIntercepts)
globalThis.LinearFromPointSlope = bundle.deepBlurize(bundle.LinearFromPointSlope)
globalThis.LinearFromTwoPoints = bundle.deepBlurize(bundle.LinearFromTwoPoints)
globalThis.LongDivision = bundle.deepBlurize(bundle.LongDivision)
globalThis.LowerQ = bundle.deepBlurize(bundle.LowerQ)
globalThis.LowerQAt = bundle.deepBlurize(bundle.LowerQAt)
globalThis.LucasSequence = bundle.deepBlurize(bundle.LucasSequence)
globalThis.Max = bundle.deepBlurize(bundle.Max)
globalThis.MaximizeField = bundle.deepBlurize(bundle.MaximizeField)
globalThis.MaximizePoint = bundle.deepBlurize(bundle.MaximizePoint)
globalThis.Mean = bundle.deepBlurize(bundle.Mean)
globalThis.Median = bundle.deepBlurize(bundle.Median)
globalThis.MedianAt = bundle.deepBlurize(bundle.MedianAt)
globalThis.Mid = bundle.deepBlurize(bundle.Mid)
globalThis.Mid3D = bundle.deepBlurize(bundle.Mid3D)
globalThis.Min = bundle.deepBlurize(bundle.Min)
globalThis.MinimizeField = bundle.deepBlurize(bundle.MinimizeField)
globalThis.MinimizePoint = bundle.deepBlurize(bundle.MinimizePoint)
globalThis.Mode = bundle.deepBlurize(bundle.Mode)
globalThis.Move = bundle.deepBlurize(bundle.Move)
globalThis.MoveX = bundle.deepBlurize(bundle.MoveX)
globalThis.MoveY = bundle.deepBlurize(bundle.MoveY)
globalThis.OnCircle = bundle.deepBlurize(bundle.OnCircle)
globalThis.OptimizeField = bundle.deepBlurize(bundle.OptimizeField)
globalThis.OptimizePoint = bundle.deepBlurize(bundle.OptimizePoint)
globalThis.Orthocentre = bundle.deepBlurize(bundle.Orthocentre)
globalThis.PairTable = bundle.deepBlurize(bundle.PairTable)
globalThis.Partition = bundle.deepBlurize(bundle.Partition)
globalThis.PdFoot = bundle.deepBlurize(bundle.PdFoot)
globalThis.PdFoot3D = bundle.deepBlurize(bundle.PdFoot3D)
globalThis.PhyConst = bundle.PhyConst
globalThis.PhyEq = bundle.PhyEq
globalThis.PolToRect = bundle.deepBlurize(bundle.PolToRect)
globalThis.PolarDiff = bundle.deepBlurize(bundle.PolarDiff)
globalThis.PolarReduce = bundle.deepBlurize(bundle.PolarReduce)
globalThis.PolyFunction = bundle.deepBlurize(bundle.PolyFunction)
globalThis.PolyPrint = bundle.deepBlurize(bundle.PolyPrint)
globalThis.PolySimplify = bundle.deepBlurize(bundle.PolySimplify)
globalThis.PolySort = bundle.deepBlurize(bundle.PolySort)
globalThis.PrimeFactorize = bundle.deepBlurize(bundle.PrimeFactorize)
globalThis.PrimeFactors = bundle.deepBlurize(bundle.PrimeFactors)
globalThis.Product = bundle.deepBlurize(bundle.Product)
globalThis.Pyth = bundle.deepBlurize(bundle.Pyth)
globalThis.PythLeg = bundle.deepBlurize(bundle.PythLeg)
globalThis.Quadrant = bundle.deepBlurize(bundle.Quadrant)
globalThis.QuadraticFromRoot = bundle.deepBlurize(bundle.QuadraticFromRoot)
globalThis.QuadraticFromVertex = bundle.deepBlurize(bundle.QuadraticFromVertex)
globalThis.QuadraticRoot = bundle.deepBlurize(bundle.QuadraticRoot)
globalThis.QuadraticSequence = bundle.deepBlurize(bundle.QuadraticSequence)
globalThis.QuadraticVertex = bundle.deepBlurize(bundle.QuadraticVertex)
globalThis.Radian = bundle.deepBlurize(bundle.Radian)
globalThis.Ratio = bundle.deepBlurize(bundle.Ratio)
globalThis.RectToPol = bundle.deepBlurize(bundle.RectToPol)
globalThis.ReflectX = bundle.deepBlurize(bundle.ReflectX)
globalThis.ReflectY = bundle.deepBlurize(bundle.ReflectY)
globalThis.RegularPolygon = bundle.deepBlurize(bundle.RegularPolygon)
globalThis.RndAngles = bundle.deepBlurize(bundle.RndAngles)
globalThis.RndCapitals = bundle.deepBlurize(bundle.RndCapitals)
globalThis.RndComposite = bundle.deepBlurize(bundle.RndComposite)
globalThis.RndConvexPolygon = bundle.deepBlurize(bundle.RndConvexPolygon)
globalThis.RndData = bundle.deepBlurize(bundle.RndData)
globalThis.RndEven = bundle.deepBlurize(bundle.RndEven)
globalThis.RndHe = bundle.deepBlurize(bundle.RndHe)
globalThis.RndLetters = bundle.deepBlurize(bundle.RndLetters)
globalThis.RndN = bundle.deepBlurize(bundle.RndN)
globalThis.RndNs = bundle.deepBlurize(bundle.RndNs)
globalThis.RndOdd = bundle.deepBlurize(bundle.RndOdd)
globalThis.RndOnCircle = bundle.deepBlurize(bundle.RndOnCircle)
globalThis.RndP = bundle.deepBlurize(bundle.RndP)
globalThis.RndPartition = bundle.deepBlurize(bundle.RndPartition)
globalThis.RndPick = bundle.deepBlurize(bundle.RndPick)
globalThis.RndPickN = bundle.deepBlurize(bundle.RndPickN)
globalThis.RndPickUnique = bundle.deepBlurize(bundle.RndPickUnique)
globalThis.RndPoint = bundle.deepBlurize(bundle.RndPoint)
globalThis.RndPointPolar = bundle.deepBlurize(bundle.RndPointPolar)
globalThis.RndPoints = bundle.deepBlurize(bundle.RndPoints)
globalThis.RndPoly = bundle.deepBlurize(bundle.RndPoly)
globalThis.RndPolynomial = bundle.deepBlurize(bundle.RndPolynomial)
globalThis.RndPyth = bundle.deepBlurize(bundle.RndPyth)
globalThis.RndQ = bundle.deepBlurize(bundle.RndQ)
globalThis.RndQs = bundle.deepBlurize(bundle.RndQs)
globalThis.RndR = bundle.deepBlurize(bundle.RndR)
globalThis.RndRatio = bundle.deepBlurize(bundle.RndRatio)
globalThis.RndRs = bundle.deepBlurize(bundle.RndRs)
globalThis.RndShake = bundle.deepBlurize(bundle.RndShake)
globalThis.RndShakeBase = bundle.deepBlurize(bundle.RndShakeBase)
globalThis.RndShakeCombo = bundle.deepBlurize(bundle.RndShakeCombo)
globalThis.RndShakeCompoundInequality = bundle.deepBlurize(bundle.RndShakeCompoundInequality)
globalThis.RndShakeConstraint = bundle.deepBlurize(bundle.RndShakeConstraint)
globalThis.RndShakeConstraints = bundle.deepBlurize(bundle.RndShakeConstraints)
globalThis.RndShakeG = bundle.deepBlurize(bundle.RndShakeG)
globalThis.RndShakeIneq = bundle.deepBlurize(bundle.RndShakeIneq)
globalThis.RndShakeN = bundle.deepBlurize(bundle.RndShakeN)
globalThis.RndShakePoint = bundle.deepBlurize(bundle.RndShakePoint)
globalThis.RndShakePointPolar = bundle.deepBlurize(bundle.RndShakePointPolar)
globalThis.RndShakeQ = bundle.deepBlurize(bundle.RndShakeQ)
globalThis.RndShakeQuantity = bundle.deepBlurize(bundle.RndShakeQuantity)
globalThis.RndShakeR = bundle.deepBlurize(bundle.RndShakeR)
globalThis.RndShakeRatio = bundle.deepBlurize(bundle.RndShakeRatio)
globalThis.RndShakeTrig = bundle.deepBlurize(bundle.RndShakeTrig)
globalThis.RndShakeTrigValue = bundle.deepBlurize(bundle.RndShakeTrigValue)
globalThis.RndShe = bundle.deepBlurize(bundle.RndShe)
globalThis.RndShuffle = bundle.deepBlurize(bundle.RndShuffle)
globalThis.RndT = bundle.deepBlurize(bundle.RndT)
globalThis.RndTriangle = bundle.deepBlurize(bundle.RndTriangle)
globalThis.RndTrigEqv = bundle.deepBlurize(bundle.RndTrigEqv)
globalThis.RndTrigValue = bundle.deepBlurize(bundle.RndTrigValue)
globalThis.RndU = bundle.deepBlurize(bundle.RndU)
globalThis.RndZ = bundle.deepBlurize(bundle.RndZ)
globalThis.RndZs = bundle.deepBlurize(bundle.RndZs)
globalThis.Rng = bundle.deepBlurize(bundle.Rng)
globalThis.Rotate = bundle.deepBlurize(bundle.Rotate)
globalThis.Round = bundle.deepBlurize(bundle.Round)
globalThis.RoundDown = bundle.deepBlurize(bundle.RoundDown)
globalThis.RoundUp = bundle.deepBlurize(bundle.RoundUp)
globalThis.ScaleCentroidToInt = bundle.deepBlurize(bundle.ScaleCentroidToInt)
globalThis.ScaleCircumcentreToInt = bundle.deepBlurize(bundle.ScaleCircumcentreToInt)
globalThis.ScaleIncentreToInt = bundle.deepBlurize(bundle.ScaleIncentreToInt)
globalThis.ScaleOrthocentreToInt = bundle.deepBlurize(bundle.ScaleOrthocentreToInt)
globalThis.ScaleTo = bundle.deepBlurize(bundle.ScaleTo)
globalThis.Sci = bundle.deepBlurize(bundle.Sci)
globalThis.SectorArea = bundle.deepBlurize(bundle.SectorArea)
globalThis.ShakeBase = bundle.deepBlurize(bundle.ShakeBase)
globalThis.ShakeCompoundInequality = bundle.deepBlurize(bundle.ShakeCompoundInequality)
globalThis.ShakeConstraint = bundle.deepBlurize(bundle.ShakeConstraint)
globalThis.ShakeConstraints = bundle.deepBlurize(bundle.ShakeConstraints)
globalThis.ShakeG = bundle.deepBlurize(bundle.ShakeG)
globalThis.ShakeIneq = bundle.deepBlurize(bundle.ShakeIneq)
globalThis.ShakeN = bundle.deepBlurize(bundle.ShakeN)
globalThis.ShakePoint = bundle.deepBlurize(bundle.ShakePoint)
globalThis.ShakePointPolar = bundle.deepBlurize(bundle.ShakePointPolar)
globalThis.ShakeQ = bundle.deepBlurize(bundle.ShakeQ)
globalThis.ShakeQuantity = bundle.deepBlurize(bundle.ShakeQuantity)
globalThis.ShakeR = bundle.deepBlurize(bundle.ShakeR)
globalThis.ShakeRatio = bundle.deepBlurize(bundle.ShakeRatio)
globalThis.ShakeTrigValue = bundle.deepBlurize(bundle.ShakeTrigValue)
globalThis.ShortDivision = bundle.deepBlurize(bundle.ShortDivision)
globalThis.ShortDivisionBy2 = bundle.deepBlurize(bundle.ShortDivisionBy2)
globalThis.SigFig = bundle.deepBlurize(bundle.SigFig)
globalThis.Sign = bundle.deepBlurize(bundle.Sign)
globalThis.SineLawAngle = bundle.deepBlurize(bundle.SineLawAngle)
globalThis.SineLawLength = bundle.deepBlurize(bundle.SineLawLength)
globalThis.Slide = bundle.deepBlurize(bundle.Slide)
globalThis.Slide3D = bundle.deepBlurize(bundle.Slide3D)
globalThis.Slope = bundle.deepBlurize(bundle.Slope)
globalThis.SlopePd = bundle.deepBlurize(bundle.SlopePd)
globalThis.SolveAAS = bundle.deepBlurize(bundle.SolveAAS)
globalThis.SolveASA = bundle.deepBlurize(bundle.SolveASA)
globalThis.SolveSAS = bundle.deepBlurize(bundle.SolveSAS)
globalThis.SolveSSA = bundle.deepBlurize(bundle.SolveSSA)
globalThis.SolveSSS = bundle.deepBlurize(bundle.SolveSSS)
globalThis.SolveTriangle = bundle.deepBlurize(bundle.SolveTriangle)
globalThis.Sort = bundle.deepBlurize(bundle.Sort)
globalThis.SortBy = bundle.deepBlurize(bundle.SortBy)
globalThis.Sqrt = bundle.deepBlurize(bundle.Sqrt)
globalThis.StatRange = bundle.deepBlurize(bundle.StatRange)
globalThis.StdDev = bundle.deepBlurize(bundle.StdDev)
globalThis.StemAndLeaf = bundle.deepBlurize(bundle.StemAndLeaf)
globalThis.Sum = bundle.deepBlurize(bundle.Sum)
globalThis.Summary = bundle.deepBlurize(bundle.Summary)
globalThis.Table = bundle.deepBlurize(bundle.Table)
globalThis.ToBase = bundle.deepBlurize(bundle.ToBase)
globalThis.ToFrac = bundle.deepBlurize(bundle.ToFrac)
globalThis.TransformFunc = bundle.deepBlurize(bundle.TransformFunc)
globalThis.TriangleFromPoint = bundle.deepBlurize(bundle.TriangleFromPoint)
globalThis.TriangleFromVertex = bundle.deepBlurize(bundle.TriangleFromVertex)
globalThis.TrigSolve = bundle.deepBlurize(bundle.TrigSolve)
globalThis.UniMode = bundle.deepBlurize(bundle.UniMode)
globalThis.UpperQ = bundle.deepBlurize(bundle.UpperQ)
globalThis.UpperQAt = bundle.deepBlurize(bundle.UpperQAt)
globalThis.VecAdd = bundle.deepBlurize(bundle.VecAdd)
globalThis.VecAdd3D = bundle.deepBlurize(bundle.VecAdd3D)
globalThis.WholeBearing = bundle.deepBlurize(bundle.WholeBearing)
globalThis.ZScore = bundle.deepBlurize(bundle.ZScore)
globalThis.arccos = bundle.deepBlurize(bundle.arccos)
globalThis.arcsin = bundle.deepBlurize(bundle.arcsin)
globalThis.arctan = bundle.deepBlurize(bundle.arctan)
globalThis.cos = bundle.deepBlurize(bundle.cos)
globalThis.deepBlurize = bundle.deepBlurize(bundle.deepBlurize)
globalThis.differentiate = bundle.deepBlurize(bundle.differentiate)
globalThis.functionize = bundle.deepBlurize(bundle.functionize)
globalThis.getMaxDeg = bundle.deepBlurize(bundle.getMaxDeg)
globalThis.integrate = bundle.deepBlurize(bundle.integrate)
globalThis.isConstrained = bundle.deepBlurize(bundle.isConstrained)
globalThis.isLooseConstrained = bundle.deepBlurize(bundle.isLooseConstrained)
globalThis.log = bundle.deepBlurize(bundle.log)
globalThis.nCr = bundle.deepBlurize(bundle.nCr)
globalThis.nPr = bundle.deepBlurize(bundle.nPr)
globalThis.sin = bundle.deepBlurize(bundle.sin)
globalThis.tan = bundle.deepBlurize(bundle.tan)
globalThis.xPolynomial = bundle.deepBlurize(bundle.xPolynomial)

