import './Code/Assertion.ts'
import './Code/Combinatorics.ts'
import './Code/Function.ts'
import './Code/Geometry.ts'
import './Code/Latex.ts'
import './Code/LinearProgram.ts'
import './Code/Numeracy.ts'
import './Code/PhyConst.ts'
import './Code/PhyEq.ts'
import './Code/Random.ts'
import './Code/RandomShake.ts'
import './Code/RandomUtil.ts'
import './Code/Relation.ts'
import './Code/Sequence.ts'
import './Code/Stat.ts'
import './Code/Text.ts'
import './Code/Triangle.ts'
import './Code/Trigonometry.ts'
import './Code/Utility.ts'
import './Code/Vector.ts'
import './Code/Vector3D.ts'

import './Algebra/Algebra.ts'
import './Algebra/Calculus.ts'
import './Algebra/Circle.ts'
import './Algebra/Quadratic.ts'
import './Algebra/Linear.ts'
import './Algebra/Polynomial'
import './Algebra/Transform'

import './should.ts'

import './Builder/index'
