declare var a: unknown
declare var b: unknown
declare var c: unknown
declare var d: unknown
declare var e: unknown
declare var f: unknown
declare var g: unknown
declare var h: unknown
declare var i: unknown
declare var j: unknown
declare var k: unknown
declare var l: unknown
declare var m: unknown
declare var n: unknown
declare var o: unknown
declare var p: unknown
declare var q: unknown
declare var r: unknown
declare var s: unknown
declare var t: unknown
declare var u: unknown
declare var v: unknown
declare var w: unknown
declare var x: unknown
declare var y: unknown
declare var z: unknown
declare var A: unknown
declare var B: unknown
declare var C: unknown
declare var D: unknown
declare var E: unknown
declare var F: unknown
declare var G: unknown
declare var H: unknown
declare var I: unknown
declare var J: unknown
declare var K: unknown
declare var L: unknown
declare var M: unknown
declare var N: unknown
declare var O: unknown
declare var P: unknown
declare var Q: unknown
declare var R: unknown
declare var S: unknown
declare var T: unknown
declare var U: unknown
declare var V: unknown
declare var W: unknown
declare var X: unknown
declare var Y: unknown
declare var Z: unknown

declare var sections: [number | string, number][]
declare var answer: string
declare var options: object
declare var question: string
declare var solution: string
